"""Worked example: deciding whether a parked vehicle blocks the sidewalk.

    python sidewalk_demo.py                 # print the numbers
    python sidewalk_demo.py --render        # also write output/sidewalk_demo.png

This is the ANNOTATED EXPLANATION of the method. To try it on your own footage
use parking_web.py, which puts the same geometry (sidewalk_geometry.py) behind a
browser UI where you click the corners yourself.

The idea in one line: a sidewalk clicked as a QUAD gives you a homography, and a
homography turns "is this vehicle blocking the footpath" from a hard perspective
problem into measuring a gap on a flat strip.

To keep the example honest the scene is generated by a real pinhole camera model
(6m mounting, 35 degrees down), so the quad is a genuine perspective view of a
1.5 x 12m rectangle and the boxes are what a detector would really return. The
pipeline under test then only ever sees those boxes; the world coordinates are
used at the end purely to report its error.
"""

import argparse
import math
import os

import cv2
import numpy as np

import sidewalk_geometry as sg

# --- scene generator: a real camera, used only to MAKE the example ------------

CAM_HEIGHT_M = 6.0          # the mounting height from the Layer E scope note
CAM_TILT_DEG = 35.0         # looking down the street
FOCAL_PX = 900.0
FRAME_H, FRAME_W = 720, 1280

# The sidewalk in world metres: X runs along the street, Y across it.
WALK_X0, WALK_X1 = 4.0, 16.0        # 12m of street covered
WALK_Y0, WALK_Y1 = 1.0, 2.5         # 1.5m wide; Y > 2.5 is the road


def project(point):
    """World (x, y, z) metres -> image pixel. Pinhole, camera at (0,0,H) looking
    along +X and tilted down; image-down is right x fwd, so nearer ground is
    LOWER in the frame."""
    th = math.radians(CAM_TILT_DEG)
    fwd = (math.cos(th), 0.0, -math.sin(th))
    right = (0.0, 1.0, 0.0)
    down = (-math.sin(th), 0.0, -math.cos(th))
    d = (point[0], point[1], point[2] - CAM_HEIGHT_M)
    z = sum(a * b for a, b in zip(d, fwd))
    x = sum(a * b for a, b in zip(d, right))
    y = sum(a * b for a, b in zip(d, down))
    return (FOCAL_PX * x / z + FRAME_W / 2, FOCAL_PX * y / z + FRAME_H / 2)


def detection_box(x0, x1, y0, y1, height_m):
    """The axis-aligned box a detector would return for a vehicle standing on the
    ground rectangle (x0..x1, y0..y1). All eight corners are projected then
    flattened — exactly the information loss a real detector has."""
    pts = [project((x, y, z))
           for x in (x0, x1) for y in (y0, y1) for z in (0.0, height_m)]
    xs, ys = [p[0] for p in pts], [p[1] for p in pts]
    return (int(min(xs)), int(min(ys)), int(max(xs)), int(max(ys)))


# What the installer would click: four sidewalk corners, in order
#   near-building, far-building, far-kerb, near-kerb   ("near" = closest to camera)
SIDEWALK_QUAD = [
    project((WALK_X0, WALK_Y0, 0)),
    project((WALK_X1, WALK_Y0, 0)),
    project((WALK_X1, WALK_Y1, 0)),
    project((WALK_X0, WALK_Y1, 0)),
]

# (label, class, ground rectangle in world metres, height). Sidewalk is Y 1.0-2.5.
SCENE = [
    ("parked on road", "car",        (6.0, 10.5, 2.9, 4.7), 1.5),
    ("up on the walk", "motorcycle", (8.0, 10.0, 1.1, 2.1), 1.2),
    ("two wheels up",  "car",        (12.0, 16.0, 2.0, 3.8), 1.5),
]


def truth_for(rect):
    """True blocked interval and free width, from the world rectangle. The
    pipeline never sees this — it is only used to report error."""
    _, _, y0, y1 = rect
    lo, hi = max(y0, WALK_Y0), min(y1, WALK_Y1)
    if hi <= lo:
        return None, WALK_Y1 - WALK_Y0
    return (lo, hi), max(lo - WALK_Y0, WALK_Y1 - hi)


def naive_bottom_edge_span(walk, box):
    """The alternative that does NOT work, kept to show why: project the whole
    bottom edge and call it the footprint."""
    x1, _, x2, y2 = box
    (_, ay), (_, by) = walk.to_strip([(x1, y2), (x2, y2)])
    lo, hi = sorted((ay, by))
    lo, hi = max(lo, 0), min(hi, walk.width_px)
    return None if hi <= lo else (lo, hi)


def main():
    ap = argparse.ArgumentParser(description="Sidewalk obstruction worked example.")
    ap.add_argument("--render", action="store_true",
                    help="Write output/sidewalk_demo.png showing both views.")
    args = ap.parse_args()

    walk = sg.Sidewalk(SIDEWALK_QUAD, width_m=WALK_Y1 - WALK_Y0,
                       length_m=WALK_X1 - WALK_X0)

    print(f"Sidewalk {walk.length_m:.0f}m long x {walk.width_m:.2f}m wide; "
          f"minimum passable {walk.min_passable_m}m")
    print(f"Camera {CAM_HEIGHT_M}m up, {CAM_TILT_DEG:.0f} deg down, "
          f"{FRAME_W}x{FRAME_H}\n")

    head = (f"{'vehicle':<17}{'detector box':<26}{'centre':<8}"
            f"{'blocks m':<10}{'free m':<9}{'true':<7}{'verdict'}")
    print(head)
    print(f"{'':<17}{'':<26}{'in zone':<8}{'(est)':<10}{'(est)':<9}{'free':<7}")
    print("-" * len(head))

    spans, rows = [], []
    quad_i = np.int32(SIDEWALK_QUAD)
    for label, cls, rect, height in SCENE:
        box = detection_box(*rect, height)
        span = walk.footprint_span(box, cls)

        cx, cy = (box[0] + box[2]) / 2, (box[1] + box[3]) / 2
        inside = cv2.pointPolygonTest(quad_i, (float(cx), float(cy)), False) >= 0

        blocks = walk.blocked_m(span)
        encroaching = blocks >= walk.encroach_m
        if encroaching:
            spans.append(span)
        free_here = walk.free_width([span])[0] if encroaching else walk.width_m
        _, true_free = truth_for(rect)
        state = walk.verdict(free_here, encroaching)
        rows.append((label, cls, box, blocks, state))
        print(f"{label:<17}{str(box):<26}{('yes' if inside else 'no'):<8}"
              f"{blocks:<10.2f}{free_here:<9.2f}{true_free:<7.2f}{state}")

    worst, at = walk.free_width(spans)
    true_worst = min(truth_for(r)[1] for _, _, r, _ in SCENE)
    print("-" * len(head))
    print(f"\nWorst pinch: {worst:.2f}m free at {at:.1f}m along "
          f"(true {true_worst:.2f}m, error {abs(worst - true_worst):.2f}m)")
    print(f"VERDICT: {walk.verdict(worst, bool(spans))} — "
          f"minimum passable width is {walk.min_passable_m}m\n")

    # The contrast that justifies the bottom-CENTRE point plus a width prior.
    print("Same scene, scored the naive way (project the whole bottom edge):")
    for label, cls, rect, height in SCENE:
        box = detection_box(*rect, height)
        naive = naive_bottom_edge_span(walk, box)
        got = 0.0 if naive is None else (naive[1] - naive[0]) / walk.px_per_m
        true_int, _ = truth_for(rect)
        true_blocks = 0.0 if true_int is None else true_int[1] - true_int[0]
        flag = "  <-- FALSE POSITIVE" if true_blocks == 0 and got >= walk.encroach_m else ""
        print(f"  {label:<17} blocks {got:.2f}m   (true {true_blocks:.2f}m){flag}")

    if args.render:
        render(walk, rows, spans, worst, at)


def render(walk, rows, spans, worst, at):
    cam = np.full((FRAME_H, FRAME_W, 3), 38, np.uint8)
    road = np.int32([project((3, 2.5, 0)), project((18, 2.5, 0)),
                     project((18, 9.0, 0)), project((3, 9.0, 0))])
    cv2.fillPoly(cam, [road], (52, 52, 58))
    cv2.fillPoly(cam, [walk.quad.astype(np.int32)], (74, 74, 82))
    walk.draw_zone(cam)

    for label, cls, box, blocks, state in rows:
        x1, y1, x2, y2 = box
        color = {sg.BLOCKED: (60, 60, 220), sg.ENCROACHING: (40, 165, 240)}.get(
            state, (80, 200, 80))
        cv2.rectangle(cam, (x1, y1), (x2, y2), color, 2)
        gx, gy = sg.ground_point(box)
        cv2.circle(cam, (int(gx), int(gy)), 7, (0, 235, 255), -1)
        cv2.putText(cam, f"{cls} {label} [{state}]", (x1, max(y1 - 8, 12)),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.5, color, 1)
    cv2.putText(cam, "CAMERA VIEW    yellow dot = ground point (the only pixel tested)",
                (18, 32), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (235, 235, 235), 2)
    cv2.putText(cam, "blue outline = sidewalk zone, four clicked corners",
                (18, 56), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (90, 200, 250), 1)

    pad = np.full((FRAME_H, FRAME_W, 3), 38, np.uint8)
    cv2.putText(pad, "RECTIFIED SIDEWALK (top-down, to scale)", (18, 32),
                cv2.FONT_HERSHEY_SIMPLEX, 0.6, (235, 235, 235), 2)
    cv2.putText(pad, "the same three vehicles after the homography",
                (18, 56), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (170, 170, 170), 1)
    walk.draw_strip(pad, spans, worst, at, origin=(60, 130), scale=2.0)
    cv2.putText(pad, f"{walk.length_m:.0f}m along x {walk.width_m:.2f}m across"
                f"   |   red = blocked   |   min passable {walk.min_passable_m}m",
                (60, 260), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (170, 170, 170), 1)

    out_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "output")
    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, "sidewalk_demo.png")
    cv2.imwrite(path, np.vstack([cam, pad]))
    print(f"\nWrote {path}")


if __name__ == "__main__":
    main()
