"""
Django settings for lookout_backend project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Falls back to a dev-only key so `manage.py` still works out of the box if
# .env is missing, but any real deployment must set SECRET_KEY in the env.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-u_t@(tpkhtw&!b0)_&zlo58=k#8%(dr8835qq(0uv245^id=o0',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# '*' is fine here only because DEBUG=True (dev-only settings) — it lets the
# Expo app reach this server over the LAN using the dev machine's IP address,
# since "localhost" from a phone refers to the phone itself, not this machine.
# A real deployment must set ALLOWED_HOSTS to a comma-separated list of real
# hostnames in the env.
_allowed_hosts = os.environ.get('ALLOWED_HOSTS', '*')
ALLOWED_HOSTS = ['*'] if _allowed_hosts == '*' else [h.strip() for h in _allowed_hosts.split(',')]

# ngrok terminates HTTPS at its edge and forwards plain HTTP to this dev
# server, setting X-Forwarded-Proto: https on the way — without this, Django
# has no way to know the original request was secure, so
# request.build_absolute_uri() (used by AlertSerializer to resolve
# image_url/video_url against the request) would report scheme "http" even
# when the client is talking to an "https://...ngrok-free.app" tunnel,
# and a browser would then refuse to load it as mixed content from an https
# page. This also fixes a latent SECURE_SSL_REDIRECT redirect loop below:
# without it, Django would see every ngrok-forwarded request as insecure and
# redirect it to https, which ngrok would just forward as http again.
# Safe only because every request here arrives either from the dev machine
# itself or through the ngrok tunnel — never through some OTHER untrusted
# proxy that could forge this header — the same trust boundary ALLOWED_HOSTS
# above already assumes for this dev/demo deployment.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Hardening that only makes sense once this is served over HTTPS in production
# — left off under DEBUG so local http://localhost development keeps working.
if not DEBUG:
    SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'True') == 'True'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'

    # The dashboard is served from a different origin than the API, so its
    # origin must be trusted explicitly for any session-authenticated POST
    # (the JWT endpoints do not need this; the Django admin does).
    CSRF_TRUSTED_ORIGINS = [
        o.strip() for o in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',')
        if o.strip()
    ]

    # Fail loudly rather than shipping the development fallbacks to production.
    # Both of these are safe in development and dangerous in the cloud, and
    # neither announces itself when wrong - the site simply runs with a public
    # signing key, or accepts any Host header.
    if SECRET_KEY.startswith('django-insecure-'):
        raise ImproperlyConfigured(
            'SECRET_KEY is still the development fallback. Set a real '
            'SECRET_KEY in the environment before deploying with DEBUG=False.'
        )
    if ALLOWED_HOSTS == ['*']:
        raise ImproperlyConfigured(
            'ALLOWED_HOSTS is "*" with DEBUG=False. Set it to your real '
            'hostnames, e.g. ALLOWED_HOSTS=api.example.com'
        )


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'corsheaders',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serves Django's own static files (admin CSS, DRF's browsable API) straight
    # from the app process, so the cloud deploy needs no nginx in front of it.
    # Must sit immediately after SecurityMiddleware, per WhiteNoise's docs.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTH_USER_MODEL = 'core.User'

AUTHENTICATION_BACKENDS = [
    'core.auth_backends.CaseInsensitiveUsernameBackend',
]

CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'http://localhost:5174',
    'http://127.0.0.1:5174',
]
# A real deployment must add its actual frontend origin(s) here via the env,
# e.g. ALLOWED_CORS_ORIGINS=https://app.example.com,https://admin.example.com
CORS_ALLOWED_ORIGINS += [
    o.strip() for o in os.environ.get('ALLOWED_CORS_ORIGINS', '').split(',') if o.strip()
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_FILTER_BACKENDS': ('django_filters.rest_framework.DjangoFilterBackend',),
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=8),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}

ROOT_URLCONF = 'lookout_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lookout_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# SQLite by default so a fresh clone runs with no setup. In the cloud it is the
# wrong choice and quietly so: PaaS filesystems are EPHEMERAL, so every restart
# or redeploy would silently discard the database - alerts, officers, residents
# and all. Setting DATABASE_URL switches to Postgres.
#
# The on-site detection PC sets the SAME DATABASE_URL, which is what lets the
# watchers write alerts straight into the cloud database while running next to
# the cameras.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

_database_url = os.environ.get('DATABASE_URL', '')
if _database_url:
    import dj_database_url

    DATABASES['default'] = dj_database_url.parse(
        _database_url,
        conn_max_age=600,          # reuse connections; PaaS latency is real
        conn_health_checks=True,   # drop connections the provider killed
        ssl_require=os.environ.get('DATABASE_SSL', 'True') == 'True',
    )





# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# collectstatic target. Required in production: WhiteNoise serves from here, and
# without it `manage.py collectstatic` has nowhere to write.
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Media files (violation snapshots saved by the curfew detection pipeline)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# --- evidence media: shared object storage ----------------------------------
# THIS IS NOT OPTIONAL IN A CLOUD DEPLOYMENT, and the reason is the split
# architecture. The detectors run on a PC at the barangay (they need the
# cameras); the API runs in the cloud. A watcher that saves a violation JPG to
# its own local MEDIA_ROOT writes it to a disk the cloud server cannot read, so
# the dashboard would show a broken image for every alert. Pointing both at one
# S3-compatible bucket is what makes the evidence reachable.
#
# Works with AWS S3, Cloudflare R2, Backblaze B2, Supabase Storage - anything
# S3-compatible. Set AWS_STORAGE_BUCKET_NAME to switch it on; leave it unset and
# Django keeps using the local folder, which is correct for development.
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME', '')
if AWS_STORAGE_BUCKET_NAME:
    AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID', '')
    AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY', '')
    AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'auto')
    # R2/B2/Supabase need an explicit endpoint; plain AWS S3 does not.
    AWS_S3_ENDPOINT_URL = os.environ.get('AWS_S3_ENDPOINT_URL') or None
    # Public read URL base, e.g. an R2 public bucket domain or a CDN.
    AWS_S3_CUSTOM_DOMAIN = os.environ.get('AWS_S3_CUSTOM_DOMAIN') or None
    AWS_QUERYSTRING_AUTH = False      # evidence URLs are stored in Alert rows,
                                      # so they must not expire
    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = None
    STORAGES['default'] = {'BACKEND': 'storages.backends.s3.S3Storage'}

# Used to build absolute Alert.image_url values from the curfew detection
# management command (it runs outside any HTTP request, so there's no
# request object to build an absolute URL from).
SITE_BASE_URL = os.environ.get('SITE_BASE_URL', 'http://localhost:8000')


# Email (used for officer account email verification codes)

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)


# SMS (Semaphore — Philippine SMS gateway)
SEMAPHORE_API_KEY    = os.environ.get('SEMAPHORE_API_KEY', '')
SEMAPHORE_SENDER_NAME = os.environ.get('SEMAPHORE_SENDER_NAME', 'LookOut')
