# Generated by Django 6.0.6 on 2026-06-18 06:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curfew_start', models.TimeField(default=datetime.time(22, 0))),
                ('curfew_end', models.TimeField(default=datetime.time(6, 0))),
                ('curfew_age', models.PositiveSmallIntegerField(default=18)),
                ('curfew_confidence', models.PositiveSmallIntegerField(default=75)),
                ('curfew_dwell', models.PositiveSmallIntegerField(default=5)),
                ('guardian_check', models.BooleanField(default=True)),
                ('unknown_alert', models.BooleanField(default=True)),
                ('noise_enabled', models.BooleanField(default=True)),
                ('noise_threshold_db', models.PositiveSmallIntegerField(default=65)),
                ('noise_duration', models.PositiveSmallIntegerField(default=10)),
                ('waste_enabled', models.BooleanField(default=True)),
                ('waste_confidence', models.PositiveSmallIntegerField(default=70)),
                ('waste_dwell', models.PositiveSmallIntegerField(default=8)),
                ('waste_collection_start', models.TimeField(default=datetime.time(6, 0))),
                ('waste_collection_end', models.TimeField(default=datetime.time(9, 0))),
                ('alert_cooldown', models.PositiveSmallIntegerField(default=120)),
                ('evidence_retention_days', models.PositiveSmallIntegerField(default=30)),
                ('auto_dispatch', models.BooleanField(default=False)),
                ('email_alerts', models.BooleanField(default=True)),
                ('sms_alerts', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System settings',
                'verbose_name_plural': 'System settings',
            },
        ),
    ]
