# Generated by Django 6.0.6 on 2026-06-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='householdmember',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
