# Generated by Django 6.0.6 on 2026-06-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_householdmember_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
