# Generated by Django 6.0.6 on 2026-06-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_emailverificationcode_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
