# Generated by Django 6.0.6 on 2026-06-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alert_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('dispatcher', 'Dispatcher'), ('officer', 'Officer'), ('both', 'Officer & Dispatcher')], default='officer', max_length=20),
        ),
    ]
