# Generated by Django 6.0.6 on 2026-06-22 02:53

import sys

from django.db import migrations, models


def copy_officer_assigned_forward(apps, schema_editor):
    Alert = apps.get_model("core", "Alert")
    for alert in Alert.objects.exclude(officer_assigned__isnull=True):
        alert.officers_assigned.add(alert.officer_assigned_id)


def copy_officer_assigned_backward(apps, schema_editor):
    # officer_assigned was a single FK, so reversing a multi-officer alert
    # necessarily drops officers — there's no lossless way back. Pick
    # deterministically (lowest id, i.e. first one ever assigned) instead of
    # an unordered .first(), and print a warning so the drop is visible
    # instead of silent.
    Alert = apps.get_model("core", "Alert")
    for alert in Alert.objects.all():
        officers = list(alert.officers_assigned.order_by("id"))
        if not officers:
            continue
        alert.officer_assigned_id = officers[0].id
        alert.save(update_fields=["officer_assigned"])
        if len(officers) > 1:
            dropped = ", ".join(o.name for o in officers[1:])
            print(
                f"WARNING: reversing migration 0008 dropped officers "
                f"[{dropped}] from alert {alert.code} (kept {officers[0].name})",
                file=sys.stderr,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='officers_assigned',
            field=models.ManyToManyField(blank=True, related_name='alerts', to='core.officer'),
        ),
        migrations.RunPython(copy_officer_assigned_forward, copy_officer_assigned_backward),
        migrations.RemoveField(
            model_name='alert',
            name='officer_assigned',
        ),
    ]
