# Generated by Django 6.0.6 on 2026-06-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alert_officers_assigned_m2m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='curfew_confidence',
            field=models.PositiveSmallIntegerField(default=45),
        ),
    ]
