# Generated by Django 6.0.6 on 2026-07-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_curfew_confidence_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='parking_confidence',
            field=models.PositiveSmallIntegerField(default=35),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='parking_dwell',
            field=models.PositiveSmallIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='parking_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='parking_move_tolerance',
            field=models.PositiveSmallIntegerField(default=40),
        ),
    ]
