# Generated by Django 6.0.6 on 2026-07-13 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_systemsettings_parking_confidence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='purok',
        ),
        migrations.RemoveField(
            model_name='household',
            name='zone',
        ),
    ]
