# Generated by Django 6.0.6 on 2026-07-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_household_purok_remove_household_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='smoking_confidence',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='smoking_dwell',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='smoking_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
