# Generated by Django 6.0.6 on 2026-07-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_systemsettings_smoking_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='thief_confidence',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='thief_dwell',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='thief_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
