# Generated by Django 6.0.6 on 2026-07-31 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_systemsettings_thief_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='drinking_confidence',
            field=models.PositiveSmallIntegerField(default=35),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='drinking_dwell',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='drinking_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
