# Generated by Django 6.0.6 on 2026-07-31 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_systemsettings_drinking_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='drinking_end',
            field=models.TimeField(default=datetime.time(5, 0)),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='drinking_hours_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='drinking_start',
            field=models.TimeField(default=datetime.time(22, 0)),
        ),
    ]
