# Generated by Django 6.0.6 on 2026-08-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_systemsettings_drinking_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='stream_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
