# Generated by Django 6.0.6 on 2026-08-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_camera_stream_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
