# Generated by Django 6.0.6 on 2026-08-16 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alert_video_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="raw_video_url",
            field=models.URLField(blank=True),
        ),
    ]
