# Generated by Django 6.0.6 on 2026-08-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_detectionjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="drinking_group_duration",
            field=models.PositiveSmallIntegerField(default=25),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="drinking_min_group",
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
