# Generated by Django 6.0.6 on 2026-08-30 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_systemsettings_drinking_group_duration_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Citation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("violator_name", models.CharField(max_length=150)),
                (
                    "barangay_of_violation",
                    models.CharField(
                        choices=[("TETUAN", "Tetuan")], default="TETUAN", max_length=30
                    ),
                ),
                (
                    "violator_barangay",
                    models.CharField(choices=[("UNKNOWN", "Unknown")], max_length=50),
                ),
                ("match_confidence", models.FloatField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "alert",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="citations",
                        to="core.alert",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="citations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "officer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="citations",
                        to="core.officer",
                    ),
                ),
                (
                    "violations",
                    models.ManyToManyField(
                        related_name="citations", to="core.violationtype"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FaceEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "angle",
                    models.CharField(
                        choices=[
                            ("front", "Front"),
                            ("right", "Right"),
                            ("left", "Left"),
                        ],
                        max_length=10,
                    ),
                ),
                ("image", models.ImageField(upload_to="face_enrollment/")),
                ("embedding", models.JSONField()),
                ("det_score", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "person_code",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                ("full_name", models.CharField(max_length=150)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("enrolled", "Enrolled")],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("enrolled_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["person_code"],
            },
        ),
        migrations.RemoveField(
            model_name="householdmember",
            name="household",
        ),
        migrations.RemoveField(
            model_name="householdmember",
            name="guardians",
        ),
        migrations.DeleteModel(
            name="Resident",
        ),
        migrations.AddField(
            model_name="faceembedding",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="embeddings",
                to="core.person",
            ),
        ),
        migrations.AddField(
            model_name="citation",
            name="matched_person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="citations",
                to="core.person",
            ),
        ),
        migrations.DeleteModel(
            name="Household",
        ),
        migrations.DeleteModel(
            name="HouseholdMember",
        ),
        migrations.AddConstraint(
            model_name="faceembedding",
            constraint=models.UniqueConstraint(
                fields=("person", "angle"), name="unique_person_angle"
            ),
        ),
    ]
