# Generated by Django 6.0.6 on 2026-08-30 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_alert_match_confidence_alert_matched_person"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="citation",
            name="violator_name",
        ),
        migrations.AddField(
            model_name="citation",
            name="first_name_entered",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="citation",
            name="last_name_entered",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="citation",
            name="middle_name_entered",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="citation",
            name="suffix_entered",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "—"),
                    ("Jr.", "Jr."),
                    ("Sr.", "Sr."),
                    ("II", "II"),
                    ("III", "III"),
                    ("IV", "IV"),
                ],
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="citation",
            name="violator_barangay",
            field=models.CharField(
                choices=[
                    ("TUGBUNGAN", "Tugbungan"),
                    ("TETUAN", "Tetuan"),
                    ("MERCEDES", "Mercedes"),
                    ("LUNZURAN", "Lunzuran"),
                    ("TUMAGA", "Tumaga"),
                    ("UNKNOWN", "Unknown / outside Zamboanga City"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Violator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                (
                    "suffix",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "—"),
                            ("Jr.", "Jr."),
                            ("Sr.", "Sr."),
                            ("II", "II"),
                            ("III", "III"),
                            ("IV", "IV"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "normalized_name",
                    models.CharField(db_index=True, editable=False, max_length=310),
                ),
                ("aliases", models.JSONField(blank=True, default=list)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                (
                    "matched_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="violators",
                        to="core.person",
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.AddField(
            model_name="citation",
            name="violator",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="citations",
                to="core.violator",
            ),
            preserve_default=False,
        ),
    ]
