# Generated by Django 6.0.6 on 2026-08-31 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_violationtype_renames_and_merge"),
    ]

    operations = [
        migrations.AddField(
            model_name="citation",
            name="client_uuid",
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
