# Generated by Django 6.0.6 on 2026-09-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_alert_media_urls_to_relative_paths"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="edges",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="camera",
            name="edges_height",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="camera",
            name="edges_width",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="camera",
            name="obstruction_minutes",
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name="camera",
            name="obstruction_pct",
            field=models.PositiveSmallIntegerField(default=50),
        ),
    ]
