# Generated by Django 6.0.6 on 2026-09-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_camera_edges_camera_edges_height_camera_edges_width_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="drinking_cooldown_center_dist",
            field=models.FloatField(default=1.5),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="drinking_evidence_max_age",
            field=models.PositiveSmallIntegerField(default=12),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="drinking_held_dwell",
            field=models.PositiveSmallIntegerField(default=24),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="drinking_mouth_proximity",
            field=models.FloatField(default=3.0),
        ),
    ]
