# Generated by Django 6.0.6 on 2026-09-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_systemsettings_drinking_cooldown_center_dist_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detectionjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("running", "Running"),
                    ("done", "Done"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="running",
                max_length=10,
            ),
        ),
    ]
