# Generated by Django 6.0.6 on 2026-09-13 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_alter_detectionjob_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="detectionjob",
            name="camera",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="detection_jobs",
                to="core.camera",
            ),
        ),
    ]
