# Generated by Django 6.0.6 on 2026-09-24 04:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_detectionjob_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='cues',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='alert',
            name='level',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('watch', 'Watch'), ('warning', 'Warning'), ('violation', 'Violation')], max_length=10),
        ),
        migrations.AddField(
            model_name='alert',
            name='reviewed_valid',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='vlm_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='vlm_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='vlm_verdict',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='vlm_api_key',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='vlm_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='vlm_min_confidence',
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='vlm_model',
            field=models.CharField(default='claude-opus-5', max_length=60),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='vlm_provider',
            field=models.CharField(default='claude', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='vlm_timeout',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='drinking_end',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='drinking_group_duration',
            field=models.PositiveSmallIntegerField(default=600),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='drinking_start',
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
    ]
