# Generated by Django 6.0.6 on 2026-09-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_detectionjob_camera"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="obstruction_minutes",
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="obstruction_pct",
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name="camera",
            name="obstruction_minutes",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="camera",
            name="obstruction_pct",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
