# Generated by Django 6.0.6 on 2026-09-27 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alert_reviewed_at_alert_reviewed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='vlm_confidence',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='vlm_reason',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='vlm_verdict',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='vlm_api_key',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='vlm_enabled',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='vlm_min_confidence',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='vlm_model',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='vlm_provider',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='vlm_timeout',
        ),
    ]
