# Generated by Django 6.0.6 on 2026-09-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_alert_vlm_confidence_remove_alert_vlm_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='vlm_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='vlm_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='vlm_verdict',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='vlm_api_key',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='vlm_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='vlm_min_confidence',
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='vlm_model',
            field=models.CharField(default='gemini-2.5-flash', max_length=60),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='vlm_provider',
            field=models.CharField(default='gemini', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='vlm_timeout',
            field=models.PositiveSmallIntegerField(default=20),
        ),
    ]
