# Generated by Django 6.0.6 on 2026-09-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alert_vlm_confidence_alert_vlm_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='vlm_model',
            field=models.CharField(default='gemini-3.8-flash', max_length=60),
        ),
    ]
