# Generated by Django 6.0.6 on 2026-09-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_vlm_model_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='vlm_timeout',
            field=models.PositiveSmallIntegerField(default=30),
        ),
    ]
