# Generated by Django 6.0.6 on 2026-09-28 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_vlm_timeout_30'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='object_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
