# Generated by Django 6.0.6 on 2026-09-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alert_object_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='vlm_endpoint',
            field=models.CharField(default='http://localhost:11434', max_length=200),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='vlm_model',
            field=models.CharField(default='qwen3-vl:4b', max_length=60),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='vlm_provider',
            field=models.CharField(default='ollama', max_length=20),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='vlm_timeout',
            field=models.PositiveSmallIntegerField(default=60),
        ),
    ]
