# Generated by Django 6.0.6 on 2026-09-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_v3_ollama'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='vlm_frames',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='vlm_max_edge',
            field=models.PositiveSmallIntegerField(default=1024),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='vlm_send_scene',
            field=models.BooleanField(default=True),
        ),
    ]
