# Generated by Django 6.0.6 on 2026-10-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_vlm_cost_knobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
