# Generated by Django 6.0.6 on 2026-10-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_camera_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='vlm_async',
            field=models.BooleanField(default=True),
        ),
    ]
