# Generated by Django 6.0.6 on 2026-10-02 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_vlm_async"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="faceembedding",
            name="unique_person_angle",
        ),
        migrations.RemoveField(
            model_name="citation",
            name="matched_person",
        ),
        migrations.RemoveField(
            model_name="alert",
            name="matched_person",
        ),
        migrations.RemoveField(
            model_name="violator",
            name="matched_person",
        ),
        migrations.RemoveField(
            model_name="alert",
            name="match_confidence",
        ),
        migrations.RemoveField(
            model_name="citation",
            name="match_confidence",
        ),
        migrations.DeleteModel(
            name="FaceEmbedding",
        ),
        migrations.DeleteModel(
            name="Person",
        ),
    ]
