# Generated by Django 6.0.6 on 2026-10-02 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_remove_facial_recognition"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemsettings",
            name="auto_dispatch",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="curfew_age",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="curfew_confidence",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="curfew_dwell",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="curfew_end",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="curfew_start",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="email_alerts",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="guardian_check",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="noise_duration",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="noise_enabled",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="noise_threshold_db",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="sms_alerts",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="unknown_alert",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="waste_collection_end",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="waste_collection_start",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="waste_confidence",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="waste_dwell",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="waste_enabled",
        ),
    ]
