# Generated by Django 6.0.6 on 2026-10-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_remove_unused_settings_columns"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="evidence_auto_purge",
            field=models.BooleanField(default=False),
        ),
    ]
