# Generated by Django 6.0.6 on 2026-10-02 09:44

from django.db import migrations, models


def watch_to_monitoring(apps, schema_editor):
    """Spec v6: the old 0.35-0.55 'watch' band becomes Monitoring. Those rows were
    object-detected, stored events, which is exactly what Monitoring is."""
    Alert = apps.get_model("core", "Alert")
    Alert.objects.filter(level="watch").update(level="monitoring")


def monitoring_to_watch(apps, schema_editor):
    Alert = apps.get_model("core", "Alert")
    Alert.objects.filter(level="monitoring").update(level="watch")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_evidence_auto_purge"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="last_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="alert",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "None"),
                    ("monitoring", "Monitoring"),
                    ("warning", "Possible"),
                    ("violation", "Likely"),
                ],
                max_length=10,
            ),
        ),
        migrations.RunPython(watch_to_monitoring, monitoring_to_watch),
    ]
