# Generated by Django 6.0.6 on 2026-10-02 11:10

from django.db import migrations, models


def adopt_new_defaults(apps, schema_editor):
    """An existing settings row keeps its own values unless they are still the OLD defaults
    (or a non-Qwen model id left from the cloud provider), in which case it moves to the
    benchmarked ones (qwen3-vl 2B-instruct, 8 frames of 640 px)."""
    SystemSettings = apps.get_model("core", "SystemSettings")
    for row in SystemSettings.objects.all():
        # also catches the old cloud default (a Gemini model id), which Ollama cannot serve
        if row.vlm_model in ("qwen3-vl:4b", "qwen3-vl:4b-instruct", "") or "qwen" not in row.vlm_model:
            row.vlm_model = "qwen3-vl:2b-instruct"
        if row.vlm_frames == 3:
            row.vlm_frames = 8
        if row.vlm_max_edge == 1024:
            row.vlm_max_edge = 640
        if row.vlm_timeout <= 60:       # a cold model load alone can take 15-20 s
            row.vlm_timeout = 120
        row.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_monitoring_level_and_last_seen"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemsettings",
            name="vlm_api_key",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="vlm_min_confidence",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="vlm_provider",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="vlm_send_scene",
        ),
        migrations.AddField(
            model_name="alert",
            name="ai",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="vlm_frames",
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="vlm_max_edge",
            field=models.PositiveSmallIntegerField(default=640),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="vlm_model",
            field=models.CharField(default="qwen3-vl:2b-instruct", max_length=60),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="vlm_timeout",
            field=models.PositiveSmallIntegerField(default=120),
        ),
        migrations.RunPython(adopt_new_defaults, migrations.RunPython.noop),
    ]
