# Generated by Django 6.0.6 on 2026-10-02 15:00

import datetime

from django.db import migrations, models


def evening_band_to_spec(apps, schema_editor):
    """drinking_start / drinking_end used to hold the (disabled) ordinance-hours gate. They now
    hold the spec's evening band (a +5 indicator, 16:00 to midnight), so a row whose gate is off
    moves to the spec band. A row with the old gate switched ON is left as it was."""
    SystemSettings = apps.get_model("core", "SystemSettings")
    for row in SystemSettings.objects.filter(drinking_hours_enabled=False):
        row.drinking_start = datetime.time(16, 0)
        row.drinking_end = datetime.time(0, 0)
        row.save(update_fields=["drinking_start", "drinking_end"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_ai_checker_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alert",
            name="vlm_confidence",
        ),
        migrations.RemoveField(
            model_name="alert",
            name="vlm_reason",
        ),
        migrations.RemoveField(
            model_name="alert",
            name="vlm_verdict",
        ),
        migrations.AddField(
            model_name="detectionjob",
            name="recorded_at",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="holdup_loiter_seconds",
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="holdup_near_person_heights",
            field=models.FloatField(default=1.75),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="object_confirm_seconds",
            field=models.FloatField(default=2.0),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="smoking_puff_count",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="smoking_puff_window_minutes",
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="vlm_model_holdup",
            field=models.CharField(
                blank=True, default="qwen3-vl:4b-instruct", max_length=60
            ),
        ),
        migrations.RunPython(evening_band_to_spec, migrations.RunPython.noop),
    ]
