# Generated by Django 6.0.6 on 2026-10-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_spec_settings_review_cleanup"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="show_testing_tools",
            field=models.BooleanField(default=False),
        ),
    ]
