# Generated by Django 6.0.6 on 2026-10-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_show_testing_tools"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="auto_start_detection",
            field=models.BooleanField(default=False),
        ),
    ]
