# Generated by Django 6.0.6 on 2026-10-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_auto_start_detection"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alert",
            options={"ordering": ["-id"]},
        ),
        migrations.AddField(
            model_name="alert",
            name="timeline",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
