# Generated by Django 6.0.6 on 2026-10-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_alert_timeline"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="cue_hold_seconds",
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="monitoring_min_seconds",
            field=models.FloatField(default=3.0),
        ),
    ]
