# Generated by Django 6.0.6 on 2026-10-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_event_hold_and_min"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("dispatched", "Dispatched"),
                    ("acknowledged", "Dismissed"),
                    ("resolved", "Resolved"),
                ],
                default="active",
                max_length=15,
            ),
        ),
    ]
