# Generated by Django 6.0.6 on 2026-10-08 01:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_alert_peak_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('size', models.BigIntegerField()),
                ('fingerprint', models.CharField(db_index=True, max_length=200)),
                ('chunk_size', models.IntegerField(default=5242880)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('complete', 'Complete')], default='uploading', max_length=10)),
                ('staged_token', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
